### ISSUE TITLE
Nonce reuse article has wrong M1, s2 and M2 values

### ISSUE THREAD

**Issue by biemster** [opsxcq/blog#1]
First, great article!

So great actually, that I tried to retrace your steps to see how it works. I've come to the point of extracting the (r,s) values from the transaction, found R and S1, but got stuck at the M1 value.

The R value is in all the sigscripts of course, since the nonce is reused, and the S1 value i found in the inputs at index 1, but the M1 value given in your article (483483...) I found in the sigscript s value in input at index 6.

The S2 and M2 values from the article I can't find at all..

Could you also add some extra info how to obtain the M values?

EDIT:
figured out the M values, with the help of these:
https://bitcoin.stackexchange.com/questions/3374/how-to-redeem-a-basic-tx
https://bitcoin.stackexchange.com/questions/41209/how-to-sign-a-transaction-with-multiple-inputs

**Comment by biemster** [comment]
Also, the private key `KypFJ5YhPwyDV7SKiQCwmHJkjZdHVz6hmb5UcVn7eaHR5pBByLvx` results in public keys `1BGxhsLyhruBwQfbYvqUJZiKqezqtczLpW` and (compressed) `1LBaZUsohnpeiP3x28ZuZTd2iPfZ5fkGUA`, not `1FaapwdwYVVBiV6Qvkis88c2KHPoxX1Jb1` as suggested in the article.
Both these addresses are never used.

**Comment by biemster** [comment]
Since I don't have an issue anymore, and there seem to be little response I'm gonna close this so it does not show up in my list anymore.

**Comment by mrx23dot** [comment]
How come M1 is same as S7,
and S2 is same as M1?
comparing the small table to the big one.

```
assert R== 0x0f13c7c741321a95510ba98792bc9050efdce2e422be4610f162449adce92a47
assert S1==0x0b4cc3447a2793c4598e5829827f38c67f72e4c3d4688019cd94066b9e7df6b9
assert M1==0x0ab06bc2befd52cde3b2de709a642e437b8a7187cc28de72bd5aff4a896e047b

assert S2==0x44d4f1763d0910413d9e95e70b3f6066eec7a19890152c1b0c9aaf1e8aefac7f
assert M2==0xf08f973c808124b3e58d94e3d85efdd9038ad0834d62e7a1d8e128be992292eb

```
